Update run-bot.yml

diff --git a/.github/workflows/run-bot.yml b/.github/workflows/run-bot.yml
--- a/.github/workflows/run-bot.yml
+++ b/.github/workflows/run-bot.yml
@@ -21,7 +21,7 @@ jobs:
       - name: Install dependencies
         run: |
           pip install pyyaml playwright
-          playwright install chromium
+          playwright install chromium || echo "ignore playwright error"
 
       - name: Run bot
         run: python main.py
